### ISSUE TITLE
As a student buyer, I want to send an" In-person inspection request" to seller with instant purchase, so that i can examine the product before making a purchase decision and purchase it on the spot if I like it.

### ISSUE THREAD

**Issue by Ajaysimha29** [Kishan-Kumar-Zalavadia/SE_Project#3]
As a student buyer, I want to send an" In-person inspection request" to seller with instant purchase, so that i can examine the product before making a purchase decision and purchase it on the spot if I like it

**Comment by Kishan-Kumar-Zalavadia** [comment]
Acceptance Criteria:

Add a "Send In-Person Inspection Request" button on product pages.
Sellers can accept or reject requests.
Sellers can view buyer contact details.
Implement confirmation prompts.

Time Estimation: 1.5 weeks
