### ISSUE TITLE
As a student user, I want the option to participate in group purchases for educational resources like e-book, so that I can access these materials at a lower cost.

### ISSUE THREAD

**Issue by pavani7695** [Kishan-Kumar-Zalavadia/SE_Project#4]
As a student user, I want the option to participate in group purchases for educational resources like e-book, so that I can access these materials at a lower cost.

**Comment by Kishan-Kumar-Zalavadia** [comment]
Acceptance Criteria:

Indicate products eligible for group purchases.
Enable users to join groups from product listings.
Allow users to complete group purchases.
Create a database table to track users and products in group purchases.
Provide clear product eligibility indication.
Allow sellers to see users who purchased in groups.

Time Estimation: 1.5 weeks
