### ISSUE TITLE
Bonus point implementation to boost profile

### ISSUE THREAD

**Issue by pavani7695** [Kishan-Kumar-Zalavadia/SE_Project#90]

**Comment by Kishan-Kumar-Zalavadia** [comment]
Acceptance Criteria: Seamless integration of a user-friendly bonus points system with tracking, redemption, expiry, notifications, security measures, admin dashboard, and clear documentation.

Time Estimate: Approximately 1-2 weeks, including UI integration, backend development, security measures, admin dashboard, and thorough testing.

**Comment by Kishan-Kumar-Zalavadia** [comment]
Done including manual testing.
